### ISSUE TITLE
Sharpening Feature as mentioned in paper

### ISSUE THREAD

**Issue by kj-lai** [alex-sage/logo-gen#13]
Hi @alex-sage, I would like to ask if the sharpening feature you mentioned in the paper is implemented as part of the process when generating icons?

**Comment by alex-sage** [comment]
Hi @kj-lai, it is not implemented as an automated process but should easily be reproducible using one of the pre-trained models I provided. It's more of a manual process because the direction in latent space which causes the icons to appear sharper is very specific to the trained model.

In order to reproduce it, you'd need to manually select a number (I'd recommend >20) of sharp icons and a number of blurry ones. Then you can take the average latent vector for each group and subtract one from the other, which gives you the directional vector. Adding this directional vector to any other icon's latent vector will produce a shifted (e.g. blurred or sharpened) version of this icon.

The necessary tools to do this are all implemented, but not that well documented (sorry for that). If you need any further help, let me know.

**Comment by kj-lai** [comment]
thank you for the fast response, the necessary tools you mentioned refers to the latent space?

**Comment by alex-sage** [comment]
With "the necessary tools" I was mainly referring to the helper functions implemented in vector.py, which should help generating, visualizing and interpolating samples and doing vector arithmetic in latent space.

**Comment by kj-lai** [comment]
Thank you for the advice, i will close this for now.
